# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1e67f4502bb7fb09a4def41d65a41cc91c02a2e7dce30a5a5cd5130ff9e5a9dc5f18f5fe4779a11432903d6d8bf026346b66fd61fab3a2361dee3cd9be29ba4

test:
  secret_key_base: 1f96a159be214961f5b95135aa7327b03d79a56b96ceccc80e921f96ceb01192b30ecdcaaa3ede5b1ed74cee667ae9e74cef7f53868b20822daf381458e14ba1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
